---
- hosts: all
  gather_facts: no
  tasks:

  - name: '#03 - Collect confilgets facts from {{inventory_hostname}}'
    arista.cvp.cv_facts:
      facts: configlets
    register: CONFIGLETS
  - name: Print them out
    debug: 
      msg: "{{ CONFIGLETS['ansible_facts']['configlets'][0] }}"